defaults:
  - base
  - data/sun_morphology
reporting:
  inputs_subdir: exp3_sun_morphology_all_models
models:
  - model/sup_imnet
  - model/ssl_imnet
  - model/ssl_colon
protocol:
  finetune: full
  eval_split: test
  early_stop_split: val
  morphology_eval: [flat, polypoid]
  thresholds:
    primary: f1_opt_on_val
    sensitivity: youden_on_val
threshold_policy: f1_opt_on_val
