defaults:
  - base
  - data/sun_subsets
reporting:
  inputs_subdir: exp4_sun_subsets
models:
  - model/sup_imnet
  - model/ssl_imnet
  - model/ssl_colon
protocol:
  finetune: full
  eval_split: test
  early_stop_split: val
  subset_percents: [5, 10, 25, 50, 100]
  thresholds:
    primary: f1_opt_on_val
    sensitivity: youden_on_val
threshold_policy: f1_opt_on_val
